# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0003_auto_20180424_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='daily_rate',
            field=models.CharField(max_length=255),
        ),
    ]
