# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0005_treasure_primary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='primary_img',
            field=models.ImageField(default='/media/no-image-available.jpg', upload_to=b''),
        ),
    ]
