# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0006_auto_20180425_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='primary_img',
            field=models.ImageField(upload_to=b''),
        ),
    ]
