# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0007_auto_20180425_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
