# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0008_auto_20180425_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='stripe_token',
        ),
    ]
