# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0009_remove_request_stripe_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_token',
        ),
        migrations.AddField(
            model_name='order',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
