# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0010_auto_20180425_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
