# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 25, 18, 32, 42, 190000)),
        ),
    ]
