# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0014_auto_20180425_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 25, 22, 18, 29, 957000)),
        ),
    ]
