# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_treasures', '0016_auto_20180425_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateField(),
        ),
    ]
